# -*- coding: utf-8 -*-


{
    'name': 'Html Widget',
    'summary': 'Provides a widget for editing HTML fields using tinymce',
    'version': '1.0',
    'description': """Provides a widget for editing HTML fields using tinymce.""",
    'category': 'Tools',
    'depends': ['base', 'base_setup', 'web',],
    'data': [
        'security/ir.model.access.csv',
        'views/res_config_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'html_toolbar/static/lib/tinymce/tinymce.min.js',
            'html_toolbar/static/lib/tinymce/themes/modern/theme.min.js',
            'html_toolbar/static/lib/tinymce/plugins/advlist/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/anchor/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/autolink/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/autoresize/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/charmap/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/code/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/colorpicker/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/emoticons/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/autosave/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/save/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/fullpage/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/fullscreen/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/hr/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/image/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/imagetools/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/insertdatetime/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/link/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/lists/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/media/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/nonbreaking/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/pagebreak/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/paste/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/preview/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/print/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/searchreplace/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/spellchecker/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/tabfocus/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/table/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/textcolor/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/textpattern/plugin.min.js',
            'html_toolbar/static/lib/tinymce/plugins/wordcount/plugin.min.js',
            'html_toolbar/static/src/js/web_tinymce.js',
            'html_toolbar/static/lib/tinymce/skins/lightgray/content.min.css',
            'html_toolbar/static/lib/tinymce/skins/lightgray/skin.min.css',
        ],
    },
    'images': ['static/description/main_screenshot.png'],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
